user = User.create(email: "user@example.com", password: "password")
user2 = User.create(email: "user2@example.com", password: "password")
melange = Melange.create(name: "Wigilianż UEmana")
type_alc = Type.create(name: "Alkohol")
type_meat = Type.create(name: "Mięso")
party_guest = PartyGuest.create(name: "Radek", role: :organizer, user: user, melange: melange)
party_guest2 = PartyGuest.create(name: "Pandzioch", role: :organizer, user: user2, melange: melange)
ConsumePreference.create(party_guest: party_guest, type: type_alc)
ConsumePreference.create(party_guest: party_guest2, type: type_alc)
ConsumePreference.create(party_guest: party_guest, type: type_meat)
ConsumePreference.create(party_guest: party_guest2, type: type_meat)
Product.create(name: "Kurczak", party_guest: party_guest, type: type_meat, price: 3450)
Product.create(name: "Bułki", party_guest: party_guest2, type: type_meat, price: 3820)
Product.create(name: "Wołowina", party_guest: party_guest2, type: type_meat, price: 1230)
Product.create(name: "Paluszki", party_guest: party_guest, type: type_meat, price: 4560)
Product.create(name: "Wódka", party_guest: party_guest, type: type_alc, price: 5320)
Product.create(name: "Gin", party_guest: party_guest, type: type_alc, price: 4560)
Product.create(name: "Jagerek", party_guest: party_guest, type: type_alc, price: 6280)
Product.create(name: "Sliwowica", party_guest: party_guest2, type: type_alc, price: 7420)